# 1.数据操作

**张量**表示一个由数值组成的数组，这个数组可能由多个维度组成。具有一个维度的张量对应数学上的向量（一维数组），具有两个维度的张量对应数学上的矩阵（二维数组）。</br>
我们可以使用**arange**创建一个行向量x。</br>
## 1.1 基础操作

In [2]:
import torch
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
# 可以通过张量的shape属性来访问张量的形状。
x.shape

torch.Size([12])

In [7]:
# 可以通过size检查张量的大小
x.size()

torch.Size([12])

In [8]:
# 可以用reshape函数改变一个张量的形状而不改变元素数量和元素值
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [9]:
# 我们，可以通过以下方式创建一个全0或全1的张量
torch.zeros((2, 3, 4)) # 三维

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

有时我们想要通过从某个特定的概率分布中随机采样来得到张量中的每个元素的值。**例如，当我们构造数组来作为神经网络的参数时，我们通常会随机初始化参数的值，**

In [11]:
torch.randn(3, 4)
# 其中每个元素都从均值0、标准差为1的高斯分布中随机采样

tensor([[-0.0022, -1.1801,  0.4883,  0.3557],
        [ 0.6891,  0.0223,  0.1559,  0.8406],
        [-0.4567,  0.1438,  0.4234, -0.2717]])

## 1.2 运算符

对于任意具有相同形状的张量（**可以理解为矩阵的加减乘除**），常见的标准算术运算符（+、-、*、/和 \*\*）都可以被升级为按元素运算。

In [15]:
x = torch.tensor([0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
print(x+y, x-y, x*y, x/y, x**y)

tensor([ 2,  4,  6, 10]) tensor([-2,  0,  2,  6]) tensor([ 0,  4,  8, 16]) tensor([0., 1., 2., 4.]) tensor([ 0,  4, 16, 64])


In [16]:
# 求幂运算
torch.exp(x)

tensor([1.0000e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

我们还可以把多个张量连接在一起，只需要提供张量列表，并给出沿哪个轴连接。

In [19]:
X = torch.arange(12, dtype=torch.float32).reshape(3, 4)
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim = 0), torch.cat((X, Y), dim = 1)
# dim = 0 沿x轴也就是行，反之亦然

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [22]:
# 还可以以逻辑运算符构建二元张量。
X == Y, X.sum()

(tensor([[False,  True, False,  True],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor(66.))

## 1.3 广播机制
上述都是在两个张量形状相同的情况下进行的计算，而**广播机制**可以让我们在形状不同的前提下，也能使得两个张量进行运算。</br>
这种机制的工作方式如下：</br>
1.通过适当复制元素来扩展一个或两个数组，以便在转换后，两个张量具有相同形状；</br>
2.对生成的数组执行按行元素操作。</br>

In [23]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [25]:
a + b # 让a、b都变成了3 * 2 的矩阵

tensor([[0, 1],
        [1, 2],
        [2, 3]])

## 1.4 索引和切片
和python数组中一样，张量中的元素可以通过索引访问：第一个元素的所以是0，最后一个元素的索引是-1。

In [27]:
X, X[-1], X[1:3] # 左开右闭

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [29]:
# 通过指定索引将元素写入矩阵
X[1, 2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [30]:
# 还可以批量处理多个元素的值
X[0:2, :] = 12 # 将第一行、第二行，所有列的元素全部改为12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

## 1.5节省内存
执行一些操作可能会导致为结果新分配内存。

In [32]:
before = id(Y) # id()可以提供内存中引用对象的确切地址。
Y = Y + X
id(Y) == before

False

这样的原因有两个：</br>
1.我们不想总是不必要地分配内存。在机器学习中，我们可能有数百兆的参数，并且在一秒内多次更新所有的参数。通常情况下，我们希望原地执行这些更新；</br>
2.**如果我们不原地更新，其他引用仍然会指向旧的内存位置，这样我们的某些代码可能会无意中引用旧的参数**。</br>

In [34]:
# 执行原地操作,我们可以使用切片表示法将操作的结果分配给先前的数组。
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 2198600076880
id(Z): 2198600076880


In [36]:
before = id(X)
X += Y # 与切片法的效果一致
id(X) == before

True

## 1.6 转换为其他Python对象

In [37]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [38]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)